fail_on_severity: 'moderate'
fail_on_scopes:
  - 'runtime'
  - 'development'
allow_licenses:
  - 'MIT'
  - 'Apache-2.0'
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'ISC'
  - 'CC0-1.0'
  - 'Unlicense'
  - '0BSD'
deny_licenses:
  - 'GPL-2.0'
  - 'GPL-3.0'
  - 'AGPL-1.0'
  - 'AGPL-3.0'
  - 'LGPL-2.0'
  - 'LGPL-2.1'
  - 'LGPL-3.0'
allow_ghsas:
  - 'GHSA-jchw-25xp-jwwc'
  - 'GHSA-cxjh-pqwp-8mfp' 