name: Extension Release

on:
  push:
    tags:
      - 'vscode-v*'  # Trigger on tags like vscode-v1.0.0
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to marketplace'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

permissions:
  contents: write  # Required to create releases

defaults:
  run:
    working-directory: vscode-extension

jobs:
  package:
    name: Package Extension
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: vscode-extension/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Compile TypeScript
        run: npm run compile

      - name: Run tests
        run: npm test

      - name: Package extension
        run: npm run package

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: sleek-sql-extension
          path: vscode-extension/*.vsix
          retention-days: 30

  publish:
    name: Publish Extension
    runs-on: ubuntu-latest
    needs: package
    if: startsWith(github.ref, 'refs/tags/vscode-v')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download packaged extension
        uses: actions/download-artifact@v4
        with:
          name: sleek-sql-extension
          path: vscode-extension/

      # Manual publishing instructions
      - name: Manual Publishing Instructions
        run: |
          echo "To publish to the VS Code Marketplace, run:"
          echo "  npx vsce publish"
          echo "To publish to Open VSX Registry, run:"
          echo "  npx ovsx publish"
          echo "Ensure you have VSCE_PAT and OVSX_PAT set as environment variables or in your .npmrc/.ovsxrc."

      # The following steps are commented out to keep publishing manual
      # - name: Publish to VS Code Marketplace
      #   run: npx vsce publish
      #   env:
      #     VSCE_PAT: ${{ secrets.VSCE_PAT }}
      #
      # - name: Publish to Open VSX Registry
      #   run: npx ovsx publish
      #   env:
      #     OVSX_PAT: ${{ secrets.OVSX_PAT }}

      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/vscode-v')
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/vscode-v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Extract changelog for version
        if: startsWith(github.ref, 'refs/tags/vscode-v')
        id: changelog
        run: |
          # Use version from previous step
          VERSION=${{ steps.get_version.outputs.VERSION }}
          echo "Extracting changelog for version: $VERSION"
          
          # Extract the section for this version from CHANGELOG.md
          # Find the line with [VERSION] and extract until the next version or end
          awk -v version="$VERSION" '
            /^## \[/ {
              if (found) exit
              if ($0 ~ "\\[" version "\\]") {
                found = 1
                print $0
                next
              }
            }
            found && /^## \[/ { exit }
            found { print }
          ' CHANGELOG.md > release_notes.md
          
          # Set the content as output (escape for GitHub Actions)
          if [ -s release_notes.md ]; then
            {
              echo 'CHANGELOG<<EOF'
              cat release_notes.md
              echo EOF
            } >> $GITHUB_OUTPUT
          else
            echo "CHANGELOG=VS Code Extension Release ${{ steps.get_version.outputs.VERSION }}" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release for Extension
        if: startsWith(github.ref, 'refs/tags/vscode-v')
        uses: softprops/action-gh-release@v2
        with:
          files: vscode-extension/*.vsix
          tag_name: ${{ github.ref_name }}
          name: "VS Code Extension ${{ steps.get_version.outputs.VERSION }}"
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 